In [1]:
import numpy as np
import pandas as pd
from glob import glob 

In [2]:
flowfiles = sorted(glob('./CSV/*.CSV'))

In [3]:
np.size(flowfiles)

2872

In [4]:
df = []
for file in flowfiles:
    df.append(pd.read_csv(file))

In [5]:
dfall = pd.concat(df, axis=1)

In [6]:
dfall.head()

FS Lin    SS Log   FL1 Log   FL2 Log   FL3 Log   FL4 Log   FL5 Log  FS Lin  \
0   427.0  0.452041  0.140279  0.213405  0.683650  0.160077  0.140279   830.0   
1   917.0  0.620252  0.253195  0.276627  0.609630  0.203733  0.257787   391.0   
2   890.0  0.620252  0.248659  0.184568  0.592770  0.140279  0.140279   571.0   
3   855.0  0.656414  0.246862  0.248659  0.530069  0.167291  0.144721   961.0   
4   921.0  0.629973  0.212638  0.265240  0.598100  0.212638  0.162236   866.0   

     SS Log   FL1 Log  ...   FL3 Log   FL4 Log   FL5 Log  FS Lin    SS Log  \
0  0.628206  0.456709  ...  0.682772  0.191440  0.357109   273.0  0.545397   
1  0.437027  0.165403  ...  0.646730  0.233726  0.324564  1004.0  0.688913   
2  0.646730  0.485412  ...  0.643205  0.182190  0.399901   608.0  0.530973   
3  0.629090  0.321599  ...  0.651133  0.198798  0.355144   504.0  0.677507   
4  0.624672  0.371797  ...  0.445487  0.172787  0.149134   625.0  0.619368   

    FL1 Log   FL2 Log   FL3 Log   FL4 Log   FL5 Log  
0  0.218876  0.209609  0.181025  0.162678  0.143841  
1  0.434198  0.373748  0.358091  0.170233  0.232873  
2  0.341356  0.289179  0.319624  0.140279  0.150493  
3  0.363975  0.333457  0.306802  0.268065  0.167291  
4  0.386385  0.339382  0.232023  0.180448  0.152257  

[5 rows x 20104 columns]

In [7]:
allmean = dfall.mean()

In [8]:
allmean

FS Lin     663.982311
SS Log       0.554379
FL1 Log      0.205182
FL2 Log      0.202277
FL3 Log      0.589269
FL4 Log      0.181832
FL5 Log      0.161980
FS Lin     647.846675
SS Log       0.551979
FL1 Log      0.355550
FL2 Log      0.376491
FL3 Log      0.588194
FL4 Log      0.178982
FL5 Log      0.179637
FS Lin     654.394432
SS Log       0.552958
FL1 Log      0.321500
FL2 Log      0.255099
FL3 Log      0.587023
FL4 Log      0.241918
FL5 Log      0.265074
FS Lin     649.450761
SS Log       0.551180
FL1 Log      0.428255
FL2 Log      0.419017
FL3 Log      0.585546
FL4 Log      0.444936
FL5 Log      0.178783
FS Lin     653.504435
SS Log       0.555380
              ...    
FL4 Log      0.360984
FL5 Log      0.183908
FS Lin     531.122820
SS Log       0.584919
FL1 Log      0.371969
FL2 Log      0.437240
FL3 Log      0.593453
FL4 Log      0.282514
FL5 Log      0.377876
FS Lin     534.170525
SS Log       0.585394
FL1 Log      0.386405
FL2 Log      0.316586
FL3 Log      0.595179
FL4 Log   

In [9]:
allstd = dfall.std()

In [10]:
allmeant = allmean.values.reshape(1,20104)

In [11]:
allmeant

array([[6.63982311e+02, 5.54379281e-01, 2.05182417e-01, ...,
        2.95554363e-01, 1.98099321e-01, 1.74881841e-01]])

In [12]:
meanbypt = allmeant.reshape(359,56)

In [13]:
allstdt = allstd.values.reshape(1,20104)
stdbypt = allstdt.reshape(359,56)

In [14]:
meandf = pd.DataFrame(meanbypt)
stddf = pd.DataFrame(stdbypt)
meanstd = pd.concat([meandf, stddf], axis=1, ignore_index=True)

In [15]:
nmeanstd = (meanstd-meanstd.mean())/meanstd.std()

In [16]:
nmeanstd.head()

0         1         2         3         4         5         6    \
0  0.724059  0.106032 -2.068189 -1.605533  0.976610 -0.790146 -0.654122   
1 -0.598340 -0.345903  0.271800  0.520084 -1.204607 -0.318882 -0.169895   
2 -0.083755  0.831444  0.199366  0.137162 -0.082670 -0.932709 -0.601002   
3 -0.030980  0.631368 -0.945416 -0.146853 -1.031468 -0.612485  0.791507   
4  0.762673 -1.257636  0.971841  0.910076  0.036925  1.383815  0.172384   

        7         8         9    ...       102       103       104       105  \
0  0.467571  0.003707 -0.775275  ... -0.294594  1.484286  1.828793  0.437341   
1 -0.768231 -0.389929 -1.314466  ...  2.751601  0.155206  1.852962  1.282574   
2  0.350320  1.097122  0.976002  ... -0.463032 -0.316102  0.173063 -0.387059   
3 -0.079704  0.639293  1.512032  ...  0.396563  0.253226  0.720206  0.284082   
4  0.767229 -1.259603  1.010991  ... -0.833190  1.006317 -2.114181 -0.365621   

        106       107       108       109       110       111  
0  0.900965 -1.404640 -1.100869 -0.793735 -1.008740 -0.840372  
1  0.601596  2.646525  1.867702 -0.404049 -1.351440 -0.917193  
2 -0.144500 -0.722537 -0.356661  0.890634  1.142559  1.328802  
3  0.881715 -0.779484 -0.553059 -0.551742 -0.956418 -0.477104  
4 -0.414174  0.774051  0.543391 -0.774111 -0.687180 -1.247541  

[5 rows x 112 columns]

In [17]:
ntraining179 = nmeanstd.iloc[0:179]

In [18]:
test180 = nmeanstd.iloc[179:360]

In [19]:
key = pd.read_csv('AMLTraining.csv')

In [20]:
key.head()

FCSFileName  TubeNumber  SampleNumber   Label
0            1           1             1  normal
1            2           2             1  normal
2            3           3             1  normal
3            4           4             1  normal
4            5           5             1  normal

In [21]:
dfk = pd.DataFrame(key)
nkey = dfk.iloc[::8]

In [22]:
nkey.head()

FCSFileName  TubeNumber  SampleNumber   Label
0             1           1             1  normal
8             9           1             2  normal
16           17           1             3  normal
24           25           1             4  normal
32           33           1             5     aml

In [23]:
key2 = nkey['Label']== 'aml'
bikey = key2*1

In [24]:
nkey = bikey.reset_index()['Label']

In [25]:
np.shape(nkey)

(359,)

In [26]:
keydf179 = pd.DataFrame(nkey[0:179])

In [27]:
np.size(keydf179)

179

In [28]:
key179 = np.ravel(keydf179)

In [29]:
key179

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0])

In [30]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [31]:
from sklearn.svm import SVC
model = SVC()

In [32]:
model.fit(ntraining179,key179)

/Users/jliao/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [33]:
predictions = model.predict(test180)

In [34]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [48]:
param_grid = {'C': [0.1,1,10,100,200,500,800,1000], 'gamma': [10,1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [49]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid.fit(ntraining179,key179)

/Users/jliao/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 48 candidates, totalling 144 fits
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.867, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.867, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.881, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.867, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.867, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.881, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C

[CV] ....... C=200, gamma=0.01, kernel=rbf, score=0.983, total=   0.0s
[CV] C=200, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=200, gamma=0.01, kernel=rbf, score=0.933, total=   0.0s
[CV] C=200, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=200, gamma=0.01, kernel=rbf, score=0.932, total=   0.0s
[CV] C=200, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=200, gamma=0.001, kernel=rbf, score=1.000, total=   0.0s
[CV] C=200, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=200, gamma=0.001, kernel=rbf, score=0.983, total=   0.0s
[CV] C=200, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=200, gamma=0.001, kernel=rbf, score=0.915, total=   0.0s
[CV] C=200, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=200, gamma=0.0001, kernel=rbf, score=0.983, total=   0.0s
[CV] C=200, gamma=0.0001, kernel=rbf .................................
[CV] .

[Parallel(n_jobs=1)]: Done 144 out of 144 | elapsed:    0.7s finished
/Users/jliao/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 200, 500, 800, 1000],
                         'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [50]:
grid.best_params_

{'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}

In [51]:
grid.best_estimator_

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [52]:
grid_predictions = grid.predict(test180)

In [53]:
grid_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [54]:
predictlabels = []
for entry in grid_predictions:
    if entry == 0:
        entry = 'normal'
    else:
        entry = 'aml'
    print(entry)
    predictlabels.append(entry)

normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
normal
aml
normal
normal
normal
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
aml
normal
aml
normal
normal
normal
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
normal
aml
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
aml
normal
normal
normal
normal
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
aml
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
normal
aml
normal
normal
norma

In [42]:
np.shape(predictlabels)

(180,)

In [43]:
labelperfile = np.repeat(predictlabels, repeats=8, axis=0)

In [44]:
np.shape(labelperfile)

(1440,)

In [45]:
#df = pd.DataFrame(labelperfile)

In [46]:
#np.shape(df)

In [47]:
#df.to_csv('labelperfile.csv')